### PR TITLE
refactor(bootstrap): support fallback colorscheme on install

### PR DESCRIPTION
**Pull request by wroyca**
By default, Lazy uses habamax as its fallback theme during package installation. Instead, we mock a lightweight astrotheme and tell Lazy to use it.

##### Before:

image

##### After:

image

### CODE REVIEW

**Comment by loichyan** [comment]
I don't think creating our own theme is a good idea. We'll need to keep updates in sync with upstream, which more or less adds extra maintenance overhead, even if it can be automated through CI. `habamax` only appears once during installation, and at that point the theme shown doesn't seem very important since no other plugins have been installed yet; it's just a bare Neovim setup. So I prefer to simply use:

```lua
{
  install = {
    colorscheme = { "astrotheme", "habamax" },
  },
}
```

Other changes look good to me :)

**Comment by wroyca** [comment]
> I don't think creating our own theme is a good idea. 

The theme subset is extracted automatically (i.e. it's a snapshot) with mini.colors:
https://github.com/echasnovski/mini.colors/blob/9fa904dd46da5d84028478b9cc689be021732fab/doc/mini-colors.txt#L627

(c.f. *making local snapshot of some other color scheme.*)



>  We'll need to keep updates in sync with upstream, 

I'm planning to add a mechanism that automatically syncs with snapshot updates, so it won't increase the current maintenance cost. If you're still against it, we can split the commit and cherry-pick the parts we want to keep. :)

**Comment by loichyan** [comment]
> I'm planning to add a mechanism that automatically syncs with snapshot updates, so it won't increase the current maintenance cost. If you're still against it,

Thanks! But it keeps making me feel like we're copying a colorscheme that only shows up once during the initial installation. While this keeps it consistent with the main theme, it seems a bit unnecessary, after all, the user may choose a non-astrotheme theme. So let's keep it as simple as possible :)

> we can split the commit and cherry-pick the parts we want to keep.

I'm going to work on it.

**Comment by wroyca** [comment]
> > I'm planning to add a mechanism that automatically syncs with snapshot updates, so it won't increase the current maintenance cost. If you're still against it,
> 
> Thanks! But it keeps making me feel like we're copying a colorscheme that only shows up once during the initial installation. While this keeps it consistent with the main theme, it seems a bit unnecessary, after all, the user may choose a non-astrotheme theme. So let's keep it as simple as possible :)
> 
> > we can split the commit and cherry-pick the parts we want to keep.
> 
> I'm going to work on it.

Thank! Sorry for the extra work!

**Comment by wroyca** [comment]
@loichyan Here's what I actually had in mind for handling colorscheme snapshots. Specifically, this approach handles user preferences as well. For instance, if the user prefers to use "catppuccin," then the snapshot will be "catppuccin" in the user configuration. There is also a mechanism to avoid conflicts between user preferences and development builds:

```lua
--Mock a snapshot of the current colorscheme to use as a fallback in situations
--where the colorscheme module (i.e., plugin) isn't available. This can occur,
--for example, when `lazy.nvim` processes `LazyPluginSpec`.
--
--Note that this snapshot is always updated on colorscheme change via
--autocommands. See the DeltaVim spec for `mini.colors`.
function M.generate_colorscheme_snapshot()
  local get_colorscheme_variant = function()
    ---@type Colorscheme
    local colorscheme = MiniColors.get_colorscheme()
    colorscheme:compress()
    colorscheme:resolve_links()
    colorscheme:write({ name = "_deltavim_snapshot_" .. vim.o.background })
  end

  get_colorscheme_variant()
  vim.o.background = (vim.o.background == "dark") and "light" or "dark"
  get_colorscheme_variant()
  vim.o.background = (vim.o.background == "dark") and "light" or "dark"

  local function read(file_path)
    local file = assert(io.open(file_path, "r"))
    local content = file:read("*all")
    file:close()
    return content
  end

  ---@diagnostic disable-next-line: param-type-mismatch
  local snapshot_location = vim.fs.joinpath(vim.fn.stdpath("config"), "colors")

  -- This is a best effort basis disambiguation mechanism that determines where
  -- to save snapshots based on the current active colorscheme. If the session
  -- uses the default DeltaVim colorscheme, it checks for a development
  -- version. If a development version is available, it updates the snapshot
  -- path to save it in the development directory (e.g.,
  -- ~/Projects/DeltaVim/colors). If the active colorscheme is not the default,
  -- it assumes the snapshot is a personal preference and saves it in the
  -- default user config path (e.g., ~/.config/nvim/colors), as it is not
  -- intended for development purposes.
  --
  -- Note that ideally, we would prefer a more robust approach to specify the
  -- development aspect, such as via a command line option like `--devel`.
  if vim.g.colors_name == ("astrolight" or "astrodark" or "astrotheme") then
    local deltavim_path = vim.fs.joinpath(os.getenv "HOME" or os.getenv "USERPROFILE", "Projects", "DeltaVim")
    local deltavim_is_devel = vim.uv.fs_stat(deltavim_path)
    if deltavim_is_devel then
      snapshot_location = deltavim_path
    end
  end

  local snapshot = assert(io.open(vim.fs.joinpath(snapshot_location, "_deltavim_snapshot.lua"), "w"))
  local snapshot_dark = read(vim.fs.joinpath(snapshot_location, "_deltavim_snapshot_dark.lua"))
  local snapshot_light = read(vim.fs.joinpath(snapshot_location, "_deltavim_snapshot_light.lua"))

  snapshot:write("if vim.o.background == 'dark' then\n")
  snapshot:write(snapshot_dark)
  snapshot:write("\nend\n")
  snapshot:write("if vim.o.background == 'light' then\n")
  snapshot:write(snapshot_light)
  snapshot:write("\nend\n")
end
```

with

```lua
---@module "mini.colors"

---@class MiniColors
---@field setup fun(opts: table): nil
---@field get_colorscheme fun(): Colorscheme

---@class Colorscheme
---@field compress fun(): nil
---@field resolve_links fun(): nil
---@field write fun(opts: { name: string }, ...): nil

---@type LazyPluginSpec
local Spec = {
  "echasnovski/mini.colors",
  event = "VeryLazy",
  config = function(_, opts)
    require("mini.colors").setup(opts)
    vim.api.nvim_del_user_command("Colorscheme")

    -- At this point, it becomes a little tricky. We want to detect when the
    -- user sets a colorscheme and properly snapshot both the light and dark
    -- variants. To achieve this, we must nest multiple colorscheme calls.
    -- Naturally, this would result in the autocmd being triggered
    -- continuously, so we need to block generate_colorscheme_snapshot from
    -- being called multiple times.
    --
    local processing = false
    vim.api.nvim_create_autocmd("ColorScheme", {
      callback = function()
        vim.schedule(function()
          if processing == true then return end
          processing = true
          require("deltavim.internal").generate_colorscheme_snapshot()
          vim.schedule(function()
            processing = false
          end)
        end)
      end,
    })
  end
}

return Spec
```

**Comment by loichyan** [comment]
> Here's what I actually had in mind for handling colorscheme snapshots. Specifically, ...

This is amazing! However, I noticed that if users can generate a local snapshot, it means they’ve already installed the colorscheme. Therefore, lazy.nvim can load the plugin directly on startup [^1], which makes the snapshot seem pointless.

> Mock a snapshot of the current colorscheme to use as a fallback in situations where the colorscheme module (i.e., plugin) isn't available. This can occur, for example, when `lazy.nvim` processes `LazyPluginSpec`.

I haven't seen lazy.nvim launch the UI while processing specs. Once it's loaded all the specs, it should know where to find the user-specified colorscheme in `install.colorscheme` and then load it as mentioned above.

I tested it on my machine with `install.colorscheme` set to `{ "catppuccin", "habamax" }`:

image

Also, in a fresh bootstrap, I observed that once the missing plugins are installed, lazy.nvim automatically changes the startup colorscheme to my specified one.

[^1]: https://github.com/folke/lazy.nvim/blob/460e1cd8f24e364d54543a4b0e83f6f4ec1f65fb/lua/lazy/core/loader.lua#L78-L79

**Comment by wroyca** [comment]
> This is amazing! However, I noticed that if users can generate a local snapshot, it means they’ve already installed the colorscheme. Therefore, lazy.nvim can load the plugin directly on startup [1](#user-content-fn-1-52d634741267631a594307cea2933469), which makes the snapshot seem pointless.

It can, with some caveats. Specifically, if a new plugin spec needs to be installed, lazy.nvim will use `install.colorscheme` by default, even when the installed colorscheme is available. Due to that, you have to specify the installed colorscheme explicitly, like so:

```lua
install = {
  colorscheme = {
    "catppuccin",
    "habamax"
    ...
  },
},
```

This is what the snapshot handles implicitly. The `install.colorscheme` becomes:

```lua
install = {
  colorscheme = {
    "_deltavim_snapshot",
  },
},
```

Here, the snapshot is whichever theme the user wants to use by default, so the user doesn't need to explicitly change `install.colorscheme` manually anymore.


> I haven't seen lazy.nvim launch the UI while processing specs. Once it's loaded all the specs, it should know where to find the user-specified colorscheme in install.colorscheme and then load it as mentioned above.

Processing a spec that is not installed will launch the UI to handle the installation, which, in turn, will use `install.colorscheme` by default (see above). I’ll update the comment with clarification. Thanks!

> Also, in a fresh bootstrap, I observed that once the missing plugins are installed, lazy.nvim automatically changes the startup colorscheme to my specified one.

As far as I know, it will not, but your configuration will. For example, if you have a theme spec like:

```lua
lazy = false,

config = function(_, opts)
  require("catppuccin").setup(opts)
end
```

Then config will get executed as the spec is processed, which in turn will apply the colorscheme. That being said, this is ultimately a happy side effect. This is why we set a high priority to theme specs, to try and process them before other specs. \:)

One drawback (as mentioned above, but repeating here for context) is that if you add a new spec after the initial fresh bootstrap, the theme will never be loaded during the installation phase. This is because the new spec installation will trigger `install.colorscheme`, and at that point, your theme spec won’t be processed beforehand unless it's mentioned in the aforementioned field (since it's already installed).

**Comment by loichyan** [comment]
> As far as I know, it will not, but your configuration will. For example, if you have a theme spec like: ...

That's right, thanks!

> Here, the snapshot is whichever theme the user wants to use by default, so the user doesn't need to explicitly change `install.colorscheme` manually anymore.
> ...
> This is what the snapshot handles implicitly. The `install.colorscheme` becomes: ...

So, one major advantage of colorschme snapshot is that it can automatically sync the user's configured colorscheme? I think it would be much simpler to configure the colorscheme through a global option. As I mentioned in <https://github.com/loichyan/DeltaVim/pull/15#issuecomment-2274905972>, add a `DeltaVim.colorscheme` option which users can change in `init.lua`.

**Comment by wroyca** [comment]
> So, one major advantage of colorschme snapshot is that it can automatically sync the user's configured colorscheme?

Specifically, the major advantage is that it can use the user's configured colorscheme when its original source is no longer available. For instance, this can happen if the user wipes ~/.local/share/nvim/lazy, or if they set up their dotfiles on a new machine (provided they commit the snapshot beforehand). In other words, the snapshot should always be available regardless of which state lazy.nvim is in.

> think it would be much simpler to configure the colorscheme through a global option. 

Ideally this would be e.g.

```lua
install = {
  colorscheme = {
    "_deltavim_global_option"
    "_deltavim_snapshot",
  },
},
```

where `_deltavim_global_option` would source the actual colorscheme plugin, but the snapshot is available if lazy can't do so. One issue with the global option is that we have no guarantee of its availability; that is, at any point in time, it may not exist anymore. On a new machine, it wouldn't exist until lazy installs it, whereas the snapshot would. (:

It's a minor thing, but I'm one to care about minor details (as you may have figured out by now, haha). I'm still exploring how to push the idea further and improve things so that it doesn't feel too complex. There are also some cases where more thought needs to be put in. 

But so far, playing with it, I personally really love how my colorscheme is available right out of the box :)

https://github.com/user-attachments/assets/0d3a0443-fd77-4309-85eb-ae08140e8861

**Comment by loichyan** [comment]
> Ideally this would be e.g.
> 
> ```lua
> install = {
>   colorscheme = {
>     "_deltavim_global_option"
>     "_deltavim_snapshot",
>   },
> },
> ```
>
> where `_deltavim_global_option` would source the actual colorscheme plugin, ...

Actually, in my mind, this would simply be:

```lua
install = {
  colorscheme = {
    DeltaVim.colorscheme or "habamax",
    "habamax"
    "_deltavim_snapshot",
  },
},
```

Furthermore, since the user has already cloned DeltaVim to `~/.config/nvim`, we can directly import the `deltavim.*` modules. So, perhaps we can move `plugin/lazy.lua` to `DeltaVim/lua/deltavim/init.lua` and load it in `~/.config/nvim/init.lua`:

```lua
-- ~/.config/nvim/init.lua -> DeltaVim/init.lua

-- We can simply use `pcall(require, "pde")`, but that catches all errors and might lead to
-- confusion since we only want to catch the "module not found" error.
for _, searcher in ipairs(package.searchers) do
  local loader = type(searcher) == "function" and searcher "pde"
  if type(loader) == "function" then
    -- Entrypoint of user's configuration
    require "pde"
    break
  end
end

-- +++
require("deltavim").bootstrap()
```

Then, users can configure global options in the entrypoint file like this:

```lua
-- ~/.config/nvim/lua/pde.lua

DeltaVim.colorscheme = "xxx"
DeltaVim.lazy_options = {
  -- some lazy options you want to override
}
-- ...other global options
```

This way, the whole initialization process becomes much clearer. 

The above describes the future refactoring plan I have in mind (https://github.com/loichyan/DeltaVim/pull/15#issuecomment-2274905972).

> One issue with the global option is that we have no guarantee of its availability; that is, at any point in time, it may not exist anymore. On a new machine, it wouldn't exist until lazy installs it, ...

Yes, but I think this would be a rare case, and most users are primarily focused on how their initialized environment looks. This should also be the solution that lazy.nvim recommends.

> whereas the snapshot would. (:

But this also means users must save the colorscheme snapshot in their dotfiles and track it in the repository if they have one. This is the major discouragement for me, as I want to minimize what users need to track in the repository. However, for the colorscheme snapshot, this is unavoidable. 

> It's a minor thing, but I'm one to care about minor details (as you may have figured out by now, haha). I'm still exploring how to push the idea further and improve things so that it doesn't feel too complex.

Totally agree! :D I think striving for perfection is one of the greatest joys of programming. 😉 I also have a bit of a "perfectionist" streak, but I sometimes catch myself falling into the trap of "over-engineering," haha.

> There are also some cases where more thought needs to be put in.

Many colorschemes implement their own lazy loading logic for performance, and I'm not sure whether mini.colors can handle this correctly (although highlights related to lazy.nvim should always be loaded.).

---

Since this is a controversial change, we can give users the choice. We could add the snippets to the wiki or, preferably, provide a function for users to setup, such as `deltavim.setup_colorscheme_snapshot()`, or, as mentioned earlier, add an option like `DeltaVim.enable_colorscheme_snapshot` for user configuration in the future. We can merge this into the main branch if you agree to add it as an optional feature :P

**Comment by wroyca** [comment]
> Many colorschemes implement their own lazy loading logic for performance, and I'm not sure whether mini.colors can handle this correctly (although highlights related to lazy.nvim should always be loaded.).

It shouldn't and doesn't need to, since it's a subset. It should only be loaded when the initial colorscheme plugin isn't installed, loaded, or available. Once the plugin is available, it takes precedence.

That is, the snapshot will only be used under specific circumstances, and it's just a subset. First, load the snapshot until the original colorscheme plugin is installed, then once it's installed, load the original colorscheme. The snapshot should never be loaded otherwise, so there's no overhead from that side.

> Since this is a controversial change, we can give users the choice. We could add the snippets to the wiki or, preferably, provide a function for users to setup, such as deltavim.setup_colorscheme_snapshot(), or, as mentioned earlier, add an option like DeltaVim.enable_colorscheme_snapshot for user configuration in the future. We can merge this into the main branch if you agree to add it as an optional feature :P

Sounds reasonable. I'd still like to work on it a bit more beforehand, though, so I may open a different MR for review at some point in the future. :)

**Pull request merged**
